version: "3.8"

services:
  localstack:
    hostname: localstack
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.13.2
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:8080:8080"
    environment:
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=host
      - AWS_SECRET_ACCESS_KEY = "test"
      - AWS_ACCESS_KEY_ID = "test"
      - SERVICES=${SERVICES-sqs,lambda,s3,sts}
      - DEBUG=${DEBUG-1}
      - DATA_DIR=${HOST_TMP_FOLDER}/data
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d

